set_property SRC_FILE_INFO {cfile:/media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_xbar_0/pcie_bd_xbar_0_ooc.xdc rfile:../../../../../p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_xbar_0/pcie_bd_xbar_0_ooc.xdc id:1 order:EARLY scoped_inst:inst} [current_design]
set_property SRC_FILE_INFO {cfile:/media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.runs/pcie_bd_xbar_0_synth_1/dont_touch.xdc rfile:../../../dont_touch.xdc id:2} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:55 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
create_clock -period 4.000 -name aclk [get_ports aclk]
set_property src_info {type:XDC file:2 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells inst]
