set_property SRC_FILE_INFO {cfile:/media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_util_ds_buf_0_0/pcie_bd_util_ds_buf_0_0_ooc.xdc rfile:../../../../../p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_util_ds_buf_0_0/pcie_bd_util_ds_buf_0_0_ooc.xdc id:1 order:EARLY scoped_inst:U0} [current_design]
set_property SRC_FILE_INFO {cfile:/media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_util_ds_buf_0_0/pcie_bd_util_ds_buf_0_0_board.xdc rfile:../../../../../p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_util_ds_buf_0_0/pcie_bd_util_ds_buf_0_0_board.xdc id:2 order:EARLY used_in_board:yes scoped_inst:U0 prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_util_ds_buf_0_0/pcie_bd_util_ds_buf_0_0.xdc rfile:../../../../../p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_util_ds_buf_0_0/pcie_bd_util_ds_buf_0_0.xdc id:3 order:EARLY scoped_inst:U0} [current_design]
set_property SRC_FILE_INFO {cfile:/media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.runs/pcie_bd_util_ds_buf_0_0_synth_1/dont_touch.xdc rfile:../../../dont_touch.xdc id:4} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:10 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
create_clock -period 10.000 -name {IBUF_DS_P[0]} [get_ports {IBUF_DS_P[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PART_PIN pcie_mgt_clkn [get_ports {IBUF_DS_N[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PART_PIN pcie_mgt_clkp [get_ports {IBUF_DS_P[0]}]
set_property src_info {type:SCOPED_XDC file:3 line:4 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name {IBUF_DS_P[0]} [get_ports {IBUF_DS_P[0]}]
set_property src_info {type:XDC file:4 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells U0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP true [get_nets {IBUF_DS_N[0]}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP true [get_nets {IBUF_DS_P[0]}]
