# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-28799-nisitha-laptop/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xcvu9p-flga2104-2L-e
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib
    rt::set_parameter defaultVhdlWorkLib xil_defaultlib

    rt::set_parameter loadVhdl2008Libs false
    rt::set_parameter loadVhdl2019Libs false
    rt::set_parameter deferParseUntilElab true
    rt::set_parameter sortHdlCommandLine true
    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/ip_0/source
    /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ipshared/1fbb/hdl/verilog
  } {
      /tools/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      /tools/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv
      /tools/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ipshared/1fbb/hdl/qdma_v5_0_vlsyn_rfs.sv
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/pcie_bd_qdma_0_0hdl/verilog/pcie_bd_qdma_0_0_core_top.sv
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/synth/pcie_bd_qdma_0_0.sv
    }
      rt::read_verilog -include {
    /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/ip_0/source
    /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ipshared/1fbb/hdl/verilog
  } {
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ipshared/5b53/hdl/gtwizard_ultrascale_v1_7_bit_sync.v
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ipshared/5b53/hdl/gtwizard_ultrascale_v1_7_gte4_drp_arb.v
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ipshared/5b53/hdl/gtwizard_ultrascale_v1_7_gthe4_delay_powergood.v
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ipshared/5b53/hdl/gtwizard_ultrascale_v1_7_gtye4_delay_powergood.v
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ipshared/5b53/hdl/gtwizard_ultrascale_v1_7_gthe3_cpll_cal.v
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ipshared/5b53/hdl/gtwizard_ultrascale_v1_7_gthe3_cal_freqcnt.v
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ipshared/5b53/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal.v
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ipshared/5b53/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal_rx.v
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ipshared/5b53/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal_tx.v
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ipshared/5b53/hdl/gtwizard_ultrascale_v1_7_gthe4_cal_freqcnt.v
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ipshared/5b53/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal.v
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ipshared/5b53/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal_rx.v
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ipshared/5b53/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal_tx.v
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ipshared/5b53/hdl/gtwizard_ultrascale_v1_7_gtye4_cal_freqcnt.v
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ipshared/5b53/hdl/gtwizard_ultrascale_v1_7_gtwiz_buffbypass_rx.v
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ipshared/5b53/hdl/gtwizard_ultrascale_v1_7_gtwiz_buffbypass_tx.v
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ipshared/5b53/hdl/gtwizard_ultrascale_v1_7_gtwiz_reset.v
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ipshared/5b53/hdl/gtwizard_ultrascale_v1_7_gtwiz_userclk_rx.v
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ipshared/5b53/hdl/gtwizard_ultrascale_v1_7_gtwiz_userclk_tx.v
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ipshared/5b53/hdl/gtwizard_ultrascale_v1_7_gtwiz_userdata_rx.v
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ipshared/5b53/hdl/gtwizard_ultrascale_v1_7_gtwiz_userdata_tx.v
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ipshared/5b53/hdl/gtwizard_ultrascale_v1_7_reset_sync.v
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ipshared/5b53/hdl/gtwizard_ultrascale_v1_7_reset_inv_sync.v
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/ip_0/ip_0/synth/gtwizard_ultrascale_v1_7_gtye4_channel.v
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/ip_0/ip_0/synth/pcie_bd_qdma_0_0_pcie4_ip_gt_gtye4_channel_wrapper.v
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/ip_0/ip_0/synth/gtwizard_ultrascale_v1_7_gtye4_common.v
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/ip_0/ip_0/synth/pcie_bd_qdma_0_0_pcie4_ip_gt_gtye4_common_wrapper.v
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/ip_0/ip_0/synth/pcie_bd_qdma_0_0_pcie4_ip_gt_gtwizard_gtye4.v
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/ip_0/ip_0/synth/pcie_bd_qdma_0_0_pcie4_ip_gt_gtwizard_top.v
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/ip_0/ip_0/synth/pcie_bd_qdma_0_0_pcie4_ip_gt.v
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/ip_0/source/pcie_bd_qdma_0_0_pcie4_ip_gtwizard_top.v
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/ip_0/source/pcie_bd_qdma_0_0_pcie4_ip_phy_ff_chain.v
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/ip_0/source/pcie_bd_qdma_0_0_pcie4_ip_phy_pipeline.v
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/ip_0/source/pcie_bd_qdma_0_0_pcie4_ip_512b_async_fifo.v
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/ip_0/source/pcie_bd_qdma_0_0_pcie4_ip_512b_cc_intfc.v
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/ip_0/source/pcie_bd_qdma_0_0_pcie4_ip_512b_cc_output_mux.v
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/ip_0/source/pcie_bd_qdma_0_0_pcie4_ip_512b_cq_intfc.v
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/ip_0/source/pcie_bd_qdma_0_0_pcie4_ip_512b_cq_output_mux.v
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/ip_0/source/pcie_bd_qdma_0_0_pcie4_ip_512b_intfc_int.v
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/ip_0/source/pcie_bd_qdma_0_0_pcie4_ip_512b_intfc.v
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/ip_0/source/pcie_bd_qdma_0_0_pcie4_ip_512b_rc_intfc.v
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/ip_0/source/pcie_bd_qdma_0_0_pcie4_ip_512b_rc_output_mux.v
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/ip_0/source/pcie_bd_qdma_0_0_pcie4_ip_512b_rq_intfc.v
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/ip_0/source/pcie_bd_qdma_0_0_pcie4_ip_512b_rq_output_mux.v
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/ip_0/source/pcie_bd_qdma_0_0_pcie4_ip_512b_sync_fifo.v
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/ip_0/source/pcie_bd_qdma_0_0_pcie4_ip_bram_16k_int.v
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/ip_0/source/pcie_bd_qdma_0_0_pcie4_ip_bram_16k.v
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/ip_0/source/pcie_bd_qdma_0_0_pcie4_ip_bram_32k.v
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/ip_0/source/pcie_bd_qdma_0_0_pcie4_ip_bram_4k_int.v
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/ip_0/source/pcie_bd_qdma_0_0_pcie4_ip_bram_msix.v
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/ip_0/source/pcie_bd_qdma_0_0_pcie4_ip_bram_rep_int.v
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/ip_0/source/pcie_bd_qdma_0_0_pcie4_ip_bram_rep.v
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/ip_0/source/pcie_bd_qdma_0_0_pcie4_ip_bram_tph.v
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/ip_0/source/pcie_bd_qdma_0_0_pcie4_ip_bram.v
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/ip_0/source/pcie_bd_qdma_0_0_pcie4_ip_gt_gt_channel.v
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/ip_0/source/pcie_bd_qdma_0_0_pcie4_ip_gt_gt_common.v
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/ip_0/source/pcie_bd_qdma_0_0_pcie4_ip_gt_phy_clk.v
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/ip_0/source/pcie_bd_qdma_0_0_pcie4_ip_gt_phy_rst.v
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/ip_0/source/pcie_bd_qdma_0_0_pcie4_ip_gt_phy_rxeq.v
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/ip_0/source/pcie_bd_qdma_0_0_pcie4_ip_gt_phy_txeq.v
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/ip_0/source/pcie_bd_qdma_0_0_pcie4_ip_sync_cell.v
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/ip_0/source/pcie_bd_qdma_0_0_pcie4_ip_sync.v
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/ip_0/source/pcie_bd_qdma_0_0_pcie4_ip_gt_cdr_ctrl_on_eidle.v
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/ip_0/source/pcie_bd_qdma_0_0_pcie4_ip_gt_receiver_detect_rxterm.v
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/ip_0/source/pcie_bd_qdma_0_0_pcie4_ip_gt_phy_wrapper.v
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/ip_0/source/pcie_bd_qdma_0_0_pcie4_ip_init_ctrl.v
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/ip_0/source/pcie_bd_qdma_0_0_pcie4_ip_pl_eq.v
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/ip_0/source/pcie_bd_qdma_0_0_pcie4_ip_vf_decode.v
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/ip_0/source/pcie_bd_qdma_0_0_pcie4_ip_pipe.v
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/ip_0/source/pcie_bd_qdma_0_0_pcie4_ip_phy_top.v
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/ip_0/source/pcie_bd_qdma_0_0_pcie4_ip_seqnum_fifo.v
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/ip_0/source/pcie_bd_qdma_0_0_pcie4_ip_sys_clk_gen_ps.v
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/ip_0/source/pcie_bd_qdma_0_0_pcie4_ip_pcie4_uscale_core_top.v
      /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/ip_0/synth/pcie_bd_qdma_0_0_pcie4_ip.v
    }
      rt::read_vhdl -lib xpm /tools/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top pcie_bd_qdma_0_0
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-28799-nisitha-laptop/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
