"""
Constraint-file SKELETON emission for the opt-in --board flag (main.py).

Deliberately structural only: no FPGA pin/ball assignment is ever fabricated
here (this project has no verified access to either seed board's official
master constraint file), only TODO-marked placeholders. Every emitted file's
header says plainly that it has never been synthesized/implemented against
real hardware in this project -- see boards/*.json's device_part_verified.
"""
import os

from boards import validate_board


def emit_constraints(board, app_name, out_dir, top_level=None):
    """
    Emit a structural constraint-file skeleton for `board` into out_dir.
    Returns the list of paths written.

    top_level: None (default) = today's behavior exactly, {app_name}_top
        (the bare AXI4-Stream/AXI4-Lite core -- byte-identical output to
        before this parameter existed). Pass f'{app_name}_selftest_top' when
        also using --self-test: that's the module actually meant to be
        synthesized standalone (it wraps {app_name}_top with its own on-chip
        traffic generator/capture, needing no real MAC/PHY) -- {app_name}_top
        alone has no AXI4-Stream source to drive it without one. Only
        Quartus's TOP_LEVEL_ENTITY assignment uses this; Vivado's .xdc has no
        equivalent (top-level entity is a project-level setting there, not
        written into the constraint file).
    """
    validate_board(board)
    top_level = top_level or f'{app_name}_top'
    if board['vendor'] == 'xilinx':
        return [_emit_xdc(board, app_name, out_dir)]
    elif board['vendor'] == 'altera':
        return [_emit_qsf(board, app_name, out_dir, top_level), _emit_sdc(board, app_name, out_dir)]
    else:
        raise ValueError(f"no constraint-skeleton emitter for vendor '{board['vendor']}'")


def _header(board, app_name, fmt):
    verified = 'verified' if board['device_part_verified'] else 'UNVERIFIED'
    return (
        f"# {app_name}.{fmt} -- constraint-file SKELETON for board '{board['display_name']}'\n"
        f"# Generated by p4-to-rtl's --board flag. STRUCTURAL SKELETON ONLY --\n"
        f"# never synthesized/implemented against real hardware in this project.\n"
        f"# device_part: {board['device_part'] or 'UNKNOWN -- fill in from board docs'}"
        f" ({verified})\n"
        f"#   {board['device_part_note']}\n"
        f"# Pin/ball locations are intentionally NOT filled in below -- copy them\n"
        f"# from your board's official reference constraint file before using this\n"
        f"# for a real bitstream.\n\n"
    )


def _emit_xdc(board, app_name, out_dir):
    path = os.path.join(out_dir, f'{app_name}.xdc')
    with open(path, 'w') as f:
        f.write(_header(board, app_name, 'xdc'))
        f.write('## Clock -- TODO: replace period/PACKAGE_PIN/IOSTANDARD with your\n')
        f.write("## real target and the values from your board's Master XDC.\n")
        f.write('create_clock -period 10.000 -name clk [get_ports clk]\n')
        f.write('# set_property PACKAGE_PIN <TODO>   [get_ports clk]\n')
        f.write('# set_property IOSTANDARD  LVCMOS33 [get_ports clk]\n\n')
        f.write('## Reset -- TODO: fill in from your board Master XDC.\n')
        f.write('# set_property PACKAGE_PIN <TODO>   [get_ports rst_n]\n')
        f.write('# set_property IOSTANDARD  LVCMOS33 [get_ports rst_n]\n')
    return path


def _emit_qsf(board, app_name, out_dir, top_level):
    path = os.path.join(out_dir, f'{app_name}.qsf')
    with open(path, 'w') as f:
        f.write(_header(board, app_name, 'qsf'))
        f.write(f'set_global_assignment -name FAMILY "{board["device_family"]}"\n')
        f.write(f'set_global_assignment -name DEVICE {board["device_part"] or "TODO_FILL_IN_DEVICE_PART"}\n')
        f.write(f'set_global_assignment -name TOP_LEVEL_ENTITY {top_level}\n')
        f.write(f'set_global_assignment -name SDC_FILE {app_name}.sdc\n')
        # Belt-and-suspenders: the generated RTL wraps large simulation-only
        # initial-block zero-fill loops (packet buffers that would otherwise
        # exceed Quartus's default 5000-iteration procedural-loop cap) in
        # `ifndef SYNTHESIS. Quartus predefines SYNTHESIS during Analysis &
        # Synthesis in the versions checked so far, but this explicit
        # assignment guarantees it regardless of Quartus version -- found
        # necessary via a real synthesis run hitting "Loop error... must
        # terminate within 5000 iterations" before this was added.
        f.write('set_global_assignment -name VERILOG_MACRO "SYNTHESIS=1"\n\n')
        f.write('# TODO: add LOCATION assignments for clk/rst_n, taken from\n')
        f.write("# Terasic's official DE2-115 pin assignment table.\n")
    return path


def _emit_sdc(board, app_name, out_dir):
    path = os.path.join(out_dir, f'{app_name}.sdc')
    with open(path, 'w') as f:
        f.write(_header(board, app_name, 'sdc'))
        f.write('# TODO: replace period with your real target.\n')
        f.write('create_clock -name clk -period 10.000 [get_ports {clk}]\n')
    return path
