"""
Constraint-file SKELETON emission for the opt-in --board flag (main.py).

Deliberately structural only: no FPGA pin/ball assignment is ever fabricated
here (this project has no verified access to either seed board's official
master constraint file), only TODO-marked placeholders. Every emitted file's
header says plainly that it has never been synthesized/implemented against
real hardware in this project -- see boards/*.json's device_part_verified.
"""
import os

from boards import validate_board


def emit_constraints(board, app_name, out_dir):
    """
    Emit a structural constraint-file skeleton for `board` into out_dir.
    Returns the list of paths written.
    """
    validate_board(board)
    if board['vendor'] == 'xilinx':
        return [_emit_xdc(board, app_name, out_dir)]
    elif board['vendor'] == 'altera':
        return [_emit_qsf(board, app_name, out_dir), _emit_sdc(board, app_name, out_dir)]
    else:
        raise ValueError(f"no constraint-skeleton emitter for vendor '{board['vendor']}'")


def _header(board, app_name, fmt):
    verified = 'verified' if board['device_part_verified'] else 'UNVERIFIED'
    return (
        f"# {app_name}.{fmt} -- constraint-file SKELETON for board '{board['display_name']}'\n"
        f"# Generated by p4-to-rtl's --board flag. STRUCTURAL SKELETON ONLY --\n"
        f"# never synthesized/implemented against real hardware in this project.\n"
        f"# device_part: {board['device_part'] or 'UNKNOWN -- fill in from board docs'}"
        f" ({verified})\n"
        f"#   {board['device_part_note']}\n"
        f"# Pin/ball locations are intentionally NOT filled in below -- copy them\n"
        f"# from your board's official reference constraint file before using this\n"
        f"# for a real bitstream.\n\n"
    )


def _emit_xdc(board, app_name, out_dir):
    path = os.path.join(out_dir, f'{app_name}.xdc')
    with open(path, 'w') as f:
        f.write(_header(board, app_name, 'xdc'))
        f.write('## Clock -- TODO: replace period/PACKAGE_PIN/IOSTANDARD with your\n')
        f.write("## real target and the values from your board's Master XDC.\n")
        f.write('create_clock -period 10.000 -name clk [get_ports clk]\n')
        f.write('# set_property PACKAGE_PIN <TODO>   [get_ports clk]\n')
        f.write('# set_property IOSTANDARD  LVCMOS33 [get_ports clk]\n\n')
        f.write('## Reset -- TODO: fill in from your board Master XDC.\n')
        f.write('# set_property PACKAGE_PIN <TODO>   [get_ports rst_n]\n')
        f.write('# set_property IOSTANDARD  LVCMOS33 [get_ports rst_n]\n')
    return path


def _emit_qsf(board, app_name, out_dir):
    path = os.path.join(out_dir, f'{app_name}.qsf')
    with open(path, 'w') as f:
        f.write(_header(board, app_name, 'qsf'))
        f.write(f'set_global_assignment -name FAMILY "{board["device_family"]}"\n')
        f.write(f'set_global_assignment -name DEVICE {board["device_part"] or "TODO_FILL_IN_DEVICE_PART"}\n')
        f.write(f'set_global_assignment -name TOP_LEVEL_ENTITY {app_name}_top\n')
        f.write(f'set_global_assignment -name SDC_FILE {app_name}.sdc\n\n')
        f.write('# TODO: add LOCATION assignments for clk/rst_n, taken from\n')
        f.write("# Terasic's official DE2-115 pin assignment table.\n")
    return path


def _emit_sdc(board, app_name, out_dir):
    path = os.path.join(out_dir, f'{app_name}.sdc')
    with open(path, 'w') as f:
        f.write(_header(board, app_name, 'sdc'))
        f.write('# TODO: replace period with your real target.\n')
        f.write('create_clock -name clk -period 10.000 [get_ports {clk}]\n')
    return path
