"""
emit_fifo.py — Emit pkt_beat_fifo.sv: a first-word-fall-through, one-beat-per-
cycle FIFO over block RAM, used by the streaming shell for the payload path
(and, later, for anything else that has to hold a stream of beats).

Why a dedicated module rather than more logic in the top:
  * The previous TX path read payload beats out of a random-access BRAM through
    a hand-rolled 2-stage issue/commit handshake that was non-pipelined "by
    construction" -- 2 cycles per beat. That caps throughput at half line rate
    no matter what the rest of the shell does.
  * A FIFO is the natural cut-through gate: TX can pop whenever there is a
    beat, and RX can push whenever there is room. No beat-count chasing.
  * It is testable in isolation. Step 1 of docs/streaming_shell_plan.md.

Structure: a BRAM ring (write port; registered read, so it infers M9K) plus a
2-entry output skid that hides the read latency so the consumer sees plain
valid/ready with no bubbles. A read is issued whenever the skid will have room
for the word when it lands, and never for a word written this same cycle
(write-then-read of one address in one cycle is a BRAM hazard).
"""


def emit_pkt_beat_fifo(output_path):
    with open(output_path, 'w') as f:
        f.write('''// ============================================================================
// pkt_beat_fifo.sv -- first-word-fall-through FIFO over block RAM.
//
// Generated by emit_fifo.py. One beat per cycle in and out with no bubbles.
//
//   Producer: assert wr_en with wr_data; the write is taken iff !full.
//   Consumer: rd_valid means rd_data is the head entry RIGHT NOW (FWFT);
//             assert rd_en to consume it, the next entry is presented next
//             cycle if there is one.
//
// Read latency of the BRAM is hidden by a 2-entry output skid (o0 = head,
// o1 = next). A BRAM read is issued (rd_ptr advances, `pend` set) whenever the
// skid will have room for the word when it lands one cycle later:
//     room = 2 - (entries left in skid after this cycle's pop) - pend
// so the skid can never overflow and the consumer never sees a bubble while
// the RAM holds data. `cnt` counts words in the RAM not yet issued; `occupancy`
// is everything (RAM + in-flight + skid), which is what "how full am I"
// should mean to the shell.
// ============================================================================
`timescale 1ns/1ps

module pkt_beat_fifo #(
  parameter int W     = 289,   // beat payload: data + keep + last, set by the top
  parameter int DEPTH = 256,   // power of two
  parameter int AW    = 8      // log2(DEPTH)
) (
  input  logic          clk,
  input  logic          rst_n,
  // write side
  input  logic          wr_en,
  input  logic [W-1:0]  wr_data,
  output logic          full,
  // read side (first-word-fall-through)
  output logic          rd_valid,
  output logic [W-1:0]  rd_data,
  input  logic          rd_en,
  // status
  output logic [AW:0]   occupancy
);

  (* ramstyle = "M9K" *)
  logic [W-1:0]  mem [0:DEPTH-1];
  logic [AW-1:0] wr_ptr, rd_ptr;
  logic [AW:0]   cnt;          // words in RAM not yet issued to the skid

  // ── write ────────────────────────────────────────────────────────────────
  wire do_wr = wr_en && !full;
  always_ff @(posedge clk) if (do_wr) mem[wr_ptr] <= wr_data;

  // ── read issue + BRAM registered read ────────────────────────────────────
  logic          pend;         // a read was issued last cycle; word is in mem_q now
  logic [W-1:0]  mem_q;
  logic [W-1:0]  o0, o1;
  logic          v0, v1;

  wire pop = v0 && rd_en;
  // entries that will remain in the skid after this cycle's pop
  wire [1:0] skid_after_pop = {1'b0, v0} + {1'b0, v1} - {1'b0, pop};
  wire       ram_has_word   = (cnt != 0);
  wire       do_issue       = ram_has_word && ((skid_after_pop + {1'b0, pend}) < 2'd2);

  // unconditional registered read of the CURRENT rd_ptr: when do_issue
  // advances rd_ptr, mem_q holds mem[old rd_ptr] next cycle -- exactly the
  // issued word -- and `pend` says so.
  always_ff @(posedge clk) mem_q <= mem[rd_ptr];

  always_ff @(posedge clk) begin
    if (!rst_n) begin
      wr_ptr <= '0; rd_ptr <= '0; cnt <= '0; pend <= 1'b0;
      v0 <= 1'b0; v1 <= 1'b0;
    end else begin
      // pointers / RAM count
      if (do_wr)    wr_ptr <= wr_ptr + 1'b1;
      if (do_issue) rd_ptr <= rd_ptr + 1'b1;
      cnt  <= cnt + {{AW{1'b0}}, do_wr} - {{AW{1'b0}}, do_issue};
      pend <= do_issue;

      // skid: apply the pop, then land the pending word in the first free slot
      begin : skid
        logic          nv0, nv1;
        logic [W-1:0]  no0, no1;
        if (pop) begin nv0 = v1; no0 = o1; nv1 = 1'b0; no1 = o1; end
        else     begin nv0 = v0; no0 = o0; nv1 = v1;   no1 = o1; end
        if (pend) begin
          if (!nv0)      begin nv0 = 1'b1; no0 = mem_q; end
          else if (!nv1) begin nv1 = 1'b1; no1 = mem_q; end
          // else: impossible by the do_issue room check
        end
        v0 <= nv0; o0 <= no0; v1 <= nv1; o1 <= no1;
      end
    end
  end

  assign rd_valid  = v0;
  assign rd_data   = o0;
  assign full      = (cnt >= DEPTH[AW:0]);
  assign occupancy = cnt + {{AW{1'b0}}, pend} + {{AW{1'b0}}, v0} + {{AW{1'b0}}, v1};

endmodule
''')
