# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.srcs/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/pcie_bd_qdma_0_0.xci
# IP: The module: 'pcie_bd_qdma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/ip_0/pcie_bd_qdma_0_0_pcie4_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pcie_bd_qdma_0_0_pcie4_ip || ORIG_REF_NAME==pcie_bd_qdma_0_0_pcie4_ip} -quiet] -quiet

# IP: /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/ip_0/ip_0/pcie_bd_qdma_0_0_pcie4_ip_gt.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pcie_bd_qdma_0_0_pcie4_ip_gt || ORIG_REF_NAME==pcie_bd_qdma_0_0_pcie4_ip_gt} -quiet] -quiet

# XDC: /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/ip_0/ip_0/synth/pcie_bd_qdma_0_0_pcie4_ip_gt_ooc.xdc

# XDC: /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/ip_0/ip_0/synth/pcie_bd_qdma_0_0_pcie4_ip_gt.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==pcie_bd_qdma_0_0_pcie4_ip_gt || ORIG_REF_NAME==pcie_bd_qdma_0_0_pcie4_ip_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/ip_0/pcie_bd_qdma_0_0_pcie4_ip_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==pcie_bd_qdma_0_0_pcie4_ip || ORIG_REF_NAME==pcie_bd_qdma_0_0_pcie4_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/ip_0/source/ip_pcie4_uscale_plus_impl_x1y2.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==pcie_bd_qdma_0_0_pcie4_ip || ORIG_REF_NAME==pcie_bd_qdma_0_0_pcie4_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/ip_0/synth/pcie_bd_qdma_0_0_pcie4_ip_ooc.xdc

# XDC: /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/ip_0/synth/pcie_bd_qdma_0_0_pcie4_ip_late.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==pcie_bd_qdma_0_0_pcie4_ip || ORIG_REF_NAME==pcie_bd_qdma_0_0_pcie4_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/ip_0/source/ip_pcie4_uscale_plus_x1y2.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==pcie_bd_qdma_0_0_pcie4_ip || ORIG_REF_NAME==pcie_bd_qdma_0_0_pcie4_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/pcie_bd_qdma_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie_bd_qdma_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/source/pcie_bd_qdma_0_0_pcie4_uscaleplus_ip.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie_bd_qdma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/synth/pcie_bd_qdma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie_bd_qdma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.srcs/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/pcie_bd_qdma_0_0.xci
# IP: The module: 'pcie_bd_qdma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/ip_0/pcie_bd_qdma_0_0_pcie4_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pcie_bd_qdma_0_0_pcie4_ip || ORIG_REF_NAME==pcie_bd_qdma_0_0_pcie4_ip} -quiet] -quiet

# IP: /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/ip_0/ip_0/pcie_bd_qdma_0_0_pcie4_ip_gt.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pcie_bd_qdma_0_0_pcie4_ip_gt || ORIG_REF_NAME==pcie_bd_qdma_0_0_pcie4_ip_gt} -quiet] -quiet

# XDC: /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/ip_0/ip_0/synth/pcie_bd_qdma_0_0_pcie4_ip_gt_ooc.xdc

# XDC: /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/ip_0/ip_0/synth/pcie_bd_qdma_0_0_pcie4_ip_gt.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==pcie_bd_qdma_0_0_pcie4_ip_gt || ORIG_REF_NAME==pcie_bd_qdma_0_0_pcie4_ip_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/ip_0/pcie_bd_qdma_0_0_pcie4_ip_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==pcie_bd_qdma_0_0_pcie4_ip || ORIG_REF_NAME==pcie_bd_qdma_0_0_pcie4_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/ip_0/source/ip_pcie4_uscale_plus_impl_x1y2.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==pcie_bd_qdma_0_0_pcie4_ip || ORIG_REF_NAME==pcie_bd_qdma_0_0_pcie4_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/ip_0/synth/pcie_bd_qdma_0_0_pcie4_ip_ooc.xdc

# XDC: /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/ip_0/synth/pcie_bd_qdma_0_0_pcie4_ip_late.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==pcie_bd_qdma_0_0_pcie4_ip || ORIG_REF_NAME==pcie_bd_qdma_0_0_pcie4_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/ip_0/source/ip_pcie4_uscale_plus_x1y2.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==pcie_bd_qdma_0_0_pcie4_ip || ORIG_REF_NAME==pcie_bd_qdma_0_0_pcie4_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/pcie_bd_qdma_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie_bd_qdma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/source/pcie_bd_qdma_0_0_pcie4_uscaleplus_ip.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie_bd_qdma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_qdma_0_0/synth/pcie_bd_qdma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie_bd_qdma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
