# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.srcs/sources_1/bd/pcie_bd/ip/pcie_bd_util_ds_buf_0_0/pcie_bd_util_ds_buf_0_0.xci
# IP: The module: 'pcie_bd_util_ds_buf_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_util_ds_buf_0_0/pcie_bd_util_ds_buf_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie_bd_util_ds_buf_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_util_ds_buf_0_0/pcie_bd_util_ds_buf_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie_bd_util_ds_buf_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_util_ds_buf_0_0/pcie_bd_util_ds_buf_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie_bd_util_ds_buf_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.srcs/sources_1/bd/pcie_bd/ip/pcie_bd_util_ds_buf_0_0/pcie_bd_util_ds_buf_0_0.xci
# IP: The module: 'pcie_bd_util_ds_buf_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_util_ds_buf_0_0/pcie_bd_util_ds_buf_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie_bd_util_ds_buf_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_util_ds_buf_0_0/pcie_bd_util_ds_buf_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie_bd_util_ds_buf_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /media/nisitha/My_Passport/MOODLE/P4_Networking/Compiler_design/P4_CMAC_QDMA/p4_cmac_qdma_implt/p4_cmac_qdma_implt.gen/sources_1/bd/pcie_bd/ip/pcie_bd_util_ds_buf_0_0/pcie_bd_util_ds_buf_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie_bd_util_ds_buf_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
